#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

# setups

    # operand setups
    setups="
    DFSEM
    DFM
    FSM
    "

    # flag to enable computations in parallel mode
    parallel=true


#------------------------------------------------------------------------------

#######################################
# Collect results into a given path
# and clean the case for the next run
# Arguments:
#    $1 = Path to move results
# Outputs:
#    Writes info to stdout
#######################################
collect() {

    [ $# -eq 0 ] && { echo "Usage: $0 dir-model"; exit 1; }

    dirResult=results/"$1"

    if [ ! -d "$dirResult" ]
    then

        echo "      # Collecting results and settings into $dirResult"

        mkdir -p "$dirResult"

        mv -f 0 "$dirResult"
        mv -f constant "$dirResult"
        mv -f system "$dirResult"
        mv -f $(foamListTimes) "$dirResult"
        [ -d postProcessing ] && mv -f postProcessing "$dirResult"
        [ -d processor0 ] && mv -f processor* "$dirResult"
        mv -f log.* "$dirResult"

        echo "      # Cleaning up the case"

        cleanTimeDirectories
        cleanAuxiliary
        cleanPostProcessing

    else

        echo "      # Directory $dirResult already exists"
        echo "      # Skipping the computation"

    fi
}


#------------------------------------------------------------------------------

for setup in $setups
do

    echo ""
    echo "# Computations for the setup: $setup"
    echo ""

    dirSetup="setups.orig/$setup"
    cp -rfL "$dirSetup/0.orig" .
    cp -rfL "$dirSetup/constant" .
    cp -rfL "$dirSetup/system" .
    cp -rf 0.orig/ 0/

    if [ ! -d constant/polyMesh ]
    then

        runApplication blockMesh

        runApplication renumberMesh -overwrite -constant

        runApplication checkMesh -allTopology -allGeometry -constant

    fi

    if [ "$parallel" = true ]
    then

        runApplication decomposePar

        runParallel $(getApplication)

        runApplication reconstructPar

    else

        runApplication $(getApplication)

    fi

    runApplication -s columnAverage \
        postProcess -func columnAverage -latestTime

    runApplication -s sample-cellPatchConstrained \
        postProcess -func sample-cellPatchConstrained -latestTime

    runApplication -s sample-cellPoint \
        postProcess -func sample-cellPoint -latestTime

    collect "$setup"

done


#------------------------------------------------------------------------------
